E-Library/E-Library/Models/Role/RoleCreateVM.cs
using System.ComponentModel.DataAnnotations;


namespace E_Library.Models.Role

{
    public class RoleCreateVM
    {
        
        [StringLength(50)]
        [Required(ErrorMessage = "Please Provide your Role Name")]
        public string RoleName { get; set; }
        
       
    }
}

E-Library/E-Library/Models/Role/RoleDeleteVM.cs
using System.ComponentModel.DataAnnotations;

namespace E_Library.Models.Role


{
    public class RoleDeleteVM
    {
        public string Id { get; set; }
        public string RoleName { get; set; }

        
       
    }
}

E-Library/E-Library/Models/Role/RoleDetailsVM.cs
using System.ComponentModel.DataAnnotations;

namespace E_Library.Models.Role


{
    public class RoleDetailsVM
    {
        public string Id { get; set; }
        public string RoleName { get; set; }


    }
}

E-Library/E-Library/Models/Role/RoleEditVM.cs
using System.ComponentModel.DataAnnotations;

namespace E_Library.Models.Role
{
    public class RoleEditVM
    {
        public string Id { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Please Provide your Role Name")]
        public string RoleName { get; set; }

       
    }
}

E-Library/E-Library/Models/Role/RoleListVM.cs
using System.ComponentModel.DataAnnotations;

namespace E_Library.Models.Role
{
    public class RoleListVM
    {
        public string Id { get; set; }
        public string RoleName { get; set; }

       
    }
}

E-Library/E-Library/Areas/Admin/Controllers/RoleController.cs
using E_Library.Models.BooksCategory;
using E_Library.Models.EntityModels;
using E_Library.Models.Role;
using E_Library.Services;
using E_Library.Services.Abstractions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace E_Library.Areas.Admin.Controllers
{
    public class RoleController : Controller
    {
        IRoleService _roleService;
        public RoleController(IRoleService roleService)
        {
                _roleService = roleService;
        }
        public IActionResult Index()
        {
            var roleLists = _roleService.Get();
            if(!roleLists.Any())
            {
                ViewBag.Message = "Data Not Found";
                return View("_NotFound");
            }
            var roleListVMs = new List<RoleListVM>();
            foreach (var role in roleLists)
            {
                var roleVM = new RoleListVM()
                {
                    Id = role.Id,
                    RoleName = role.Name,
                };
                roleListVMs.Add(roleVM);
            }
            return View(roleListVMs);
        }
        public IActionResult Create()
        {
            return View();        
        }

        [HttpPost]
        public IActionResult Create(RoleCreateVM createModel)
        {
            if (ModelState.IsValid)
            {
               
                var roleVm = new IdentityRole()
                {
                    Name = createModel.RoleName
                };
                var result = _roleService.Create(roleVm);
                if (result.IsSucced)
                {
                    TempData["save"] = "Role Has Been Saved Successfully ";
                    ModelState.Clear();
                    return RedirectToAction(nameof(Index));

                }
                if (result.ErrorMessages.Any())
                {
                    foreach (var error in result.ErrorMessages)
                    {
                        ModelState.AddModelError("", error);
                    }
                }

            }
            return View(createModel);
        }
        public IActionResult Edit(string id)
        {
            var existingRole = _roleService.GetFirstOrDefault(x => x.Id == id);
            var roleVM = new RoleEditVM()
            {
                Id = existingRole.Id,
                RoleName = existingRole.Name

            };

            return View(roleVM);
          
        }
        [HttpPost]
        public IActionResult Edit(RoleEditVM editModel)
        {

            if (ModelState.IsValid)
            {
                var existingRole=_roleService.GetFirstOrDefault(data=>data.Id == editModel.Id);
                if(existingRole == null)
                {
                    ViewBag.Message = "Data Not Found";
                    return View("_NotFound");
                }
                existingRole.Id= editModel.Id;
                existingRole.Name = editModel.RoleName;
                var result=_roleService.Update(existingRole);
                if (result.IsSucced)
                {
                    TempData["update"] = "Role Has Been Updated Successfully ";
                    ModelState.Clear();
                    return RedirectToAction(nameof(Index));
                }
                if (result.ErrorMessages.Any())
                {
                    foreach (var error in result.ErrorMessages)
                    {
                        ModelState.AddModelError("", error);
                    }
                }
            }
            return View();
        }
        public IActionResult Delete(string id)
        {
            var existingRole = _roleService.GetFirstOrDefault(x => x.Id == id);
            var roleVM = new RoleDeleteVM()
            {
                Id = existingRole.Id,
                RoleName = existingRole.Name

            };

            return View(roleVM);

        }
        [HttpPost]
        public IActionResult Delete(RoleDeleteVM deleteModel)
        {
            var existingRole = _roleService.GetFirstOrDefault(x => x.Id == deleteModel.Id);
            if (existingRole == null)
            {
                ViewBag.Message = "Requested Page Not Found";
                return View("_NotFound");
            }
            //existingRole.Name = deleteModel.RoleName;

            var result = _roleService.Remove(existingRole);
            if (result.IsSucced)
            {
                ModelState.Clear();
                return RedirectToAction(nameof(Index));
            }
            if (result.ErrorMessages.Any())
            {
                foreach (var error in result.ErrorMessages)
                {
                    ModelState.AddModelError("", error);
                }
            }
            return View();
         
        }
    }
}

E-Library/E-Library/Views/Role/Assign.cshtml
@using E_Library.Areas.Admin.Models;
@model  RoleUserVm
@{
    ViewData["Title"] = "Assign";
}
<br />
<h2 class="text-info">Assign Role </h2>

<form asp-action="Assign" method="post" enctype="multipart/form-data">
    <div class="p-4 rounded border">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <h5>@ViewBag.message</h5>

        <div class="form-group row">
            <div class="col-2">
                <label asp-for="UserId"></label>
            </div>
            <div class="col-5">
                <select asp-for="UserId" asp-items="ViewBag.UserId" class="form-control"></select>
                @* <input asp-for="UserId" class="form-control" />*@

            </div>
            <span asp-validation-for="UserId" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RoleId"></label>
            </div>
            <div class="col-5">
             
                 <select asp-for="RoleId" asp-items="ViewBag.RoleId" class="form-control"></select>
                @* <input asp-for="SpecialTagId" class="form-control" />*@

            </div>
            <span asp-validation-for="RoleId" class="text-danger"></span>
        </div>

     

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Assign" />
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>
    </div>
</form>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial.cshtml");
    }
    <script type="text/javascript">
        $(function () {
            var done = '@TempData["done"]'
            if (done != '') {
                alertify.error(done);
            }
        })
    </script>

    <script type="text/javascript">
        $(function () {
            var save = '@TempData["save"]'
            if (save != '') {
                alertify.success(save);
            }
        })
    </script>
    }

    

E-Library/E-Library/Views/Role/AssignUserRole.cshtml
@{
    ViewData["Title"] = "AssignUserRole";
    int serialNo = 1;
}
<br />
<br />
<div class="row">
    <div class="col-6">
        <h2 class="text-info">Assign User Role  Information</h2>
    </div>
   @* <div class="col-6 text-right">
        <a asp-action="Create" class="btn btn-info"><i class="fa-solid fa-plus"></i>&nbsp; Add New Role</a>
    </div>*@
</div>
<br />
<style>
    .table-info th {
        text-align: center;
        font-family: "Trirong",serif;
    }
</style>


<div>
    <table class="table table-bordered">
        <tr class="table-info">
            <th>Serial No</th>
           @* <th>User ID</th>
            <th>Role ID</th>*@
            <th>User Name</th> 
            <th>Role Name</th>
            @*<th>Action</th>*@

        </tr>
        @foreach (var data in ViewBag.UserRoles)
        {
            <tr>
                <td>@(serialNo++)</td>
                @*<td>@data.UserId</td>
                <td>@data.RoleId</td>*@
                <td>@data.UserName</td>
                <td>@data.RoleName</td>
               @* <td>
                    <div class="btn-group">
                        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@data.Id"><i class="far fa-edit"></i></a>
                        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@data.Id"><i class="fas fa-trash-alt"></i></a>
                    </div>
                </td>*@


            </tr>
        }

    </table>
</div>

@section Scripts
    {
    <script type="text/javascript">
        $(function () {
            var save = '@TempData["save"]'
            if (save != '') {
                alertify.success(save);
            }
        })
    </script>


    <script type="text/javascript">
        $(function () {
            var edit = '@TempData["edit"]'
            if (edit != '') {
                alertify.success(edit);
            }
        })
    </script>

    <script type="text/javascript">
        $(function () {
            var lock = '@TempData["lock"]'
            if (lock != '') {
                alertify.error(lock);
            }
        })
    </script>
    <script type="text/javascript">
        $(function () {
            var lockEdit = '@TempData["lockEdit"]'
            if (lockEdit != '') {
                alertify.success(lockEdit);
            }
        })
    </script>

    <script type="text/javascript">
        $(function () {
            var done = '@TempData["done"]'
            if (done != '') {
                alertify.error(done);
            }
        })
    </script>

}

E-Library/E-Library/Views/Role/Create.cshtml
@model E_Library.Models.Role.RoleCreateVM
@{
    ViewData["Title"] = "Create";
}
<br />

<h1 style="text-align:center;color:green">Role Create Form</h1>
<hr />

<div class="row">

    <form asp-action="Create" method="post">
        <div class="p-4 rounded border row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4 text-black">
                        <label asp-for="RoleName"></label>
                    </div>
                    <div class="col-8">

                        <input asp-for="RoleName" class="form-control" />

                    </div>
                    <span asp-validation-for="RoleName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-outline-success" value="Create" />
                    <a class="btn btn-outline-info" asp-action="Index" asp-controller="Role"><i class="fa-solid fa-arrow-right-to-bracket"></i>&nbsp; Back To List</a>
                </div>
            </div>
        </div>

    </form>

</div>

@section scripts{
    <partial name="~/Views/Shared/_ValidationScriptsPartial.cshtml"></partial>
    <script src="#"></script>
}

E-Library/E-Library/Views/Role/Delete.cshtml
@model E_Library.Models.Role.RoleDeleteVM
@{
    ViewData["Title"] = "Delete";
}
<br />
<h2 class="text-info">Role Deletion Form</h2>

<div>
  
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>

    </dl>

    <form asp-action="Delete">
        <h4 class="text-danger">Do you want to Delete this Role..?</h4>
        <input type="submit" class="btn btn-outline-danger" value="Delete Data" />
        <a class="btn btn-outline-info" asp-action="Index" asp-controller="Role"> <i class="fa-solid fa-arrow-right-to-bracket"></i>&nbsp;Back To List</a>

    </form>
</div>

E-Library/E-Library/Views/Role/Edit.cshtml
@model E_Library.Models.Role.RoleEditVM
@{
    ViewData["Title"] = "Edit";
}
<br />
<h2 class="text-info">Role Updatation Form</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>


            <div class="form-group">

                <input type="submit" class="btn btn-outline-success" value="Update Data" />
                <a class="btn btn-outline-info" asp-action="Index" asp-controller="Role"><i class="fa-solid fa-arrow-right-to-bracket"></i>&nbsp; Back To List</a>
            </div>
        </form>
    </div>
</div>

E-Library/E-Library/Views/Role/Index.cshtml
@using E_Library.Models.Role
@model IEnumerable<RoleListVM>
@{
    ViewData["Title"] = "Index";
    int serialNo = 1;
}
<br />
<br />
<h1 style="text-align:center;color:green;">List of Roles</h1>
@*<div class="row">
    <div class="col-6">
        <h2 class="text-info text-center"></h2>
    </div>
    
</div>*@
<div class="col-6 text-right">
    <a asp-action="Create" class="btn btn-info"><i class="fa-solid fa-plus"></i>&nbsp; Add New Role</a>
    
</div>
<br />
<style>
    .table-info th {
        text-align: center;
        font-family: "Trirong",serif;
    }
</style> 


<div>
    <table class="table table-bordered text-center">
        <tr class="table-info">
            <th>Serial No</th>
            <th>Name</th>
            <th>Action</th>

        </tr>
        @foreach (var data in Model)
        {
            <tr>
                <td>@(serialNo++)</td>
                <td>@data.RoleName</td>
                <td>
                    <div class="btn-group">
                        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@data.Id"><i class="far fa-edit"></i></a>
                        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@data.Id"><i class="fas fa-trash-alt"></i></a>
                    </div>
                </td>
                
               
            </tr>
        }

    </table>
</div>

@section Scripts
    {
    <script type="text/javascript">
        $(function () {
            var save = '@TempData["save"]'
            if (save != '') {
                alertify.success(save);
            }
        })
    </script>


    <script type="text/javascript">
        $(function () {
            var edit = '@TempData["edit"]'
            if (edit != '') {
                alertify.success(edit);
            }
        })
    </script>

   

    <script type="text/javascript">
        $(function () {
            var done = '@TempData["done"]'
            if (done != '') {
                alertify.error(done);
            }
        })
    </script>

}