E-Library/E-Library/Areas/Admin/Controllers/AuthorController.cs
using E_Library.Models.BooksAuthor;
using E_Library.Models.BooksCategory;
using E_Library.Models.EntityModels;
using E_Library.Services;
using E_Library.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace E_Library.Areas.Admin.Controllers
{
    public class AuthorController : Controller
    {

        IAuthorService _authorService;
        public AuthorController(IAuthorService authorService)
        {
            _authorService = authorService;
        }

        public IActionResult Index()
        {
            var authors = _authorService.Get();
            if (!authors.Any())
            {
                ViewBag.Message = "No Data Found";
                return View("_NotFound");
            }
            var authorListVMs = new List<AuthorListVM>();

            foreach (var author in authors)
            {

                // var categoryVM = _mapper.Map<CategoryListVM>(category);
                var categoryVM = new AuthorListVM()
                {
                    Id = author.Id,
                    AuthorName = author.AuthorName,
                    Description = author.Description
                };
                authorListVMs.Add(categoryVM);
            }
            return View(authorListVMs);

        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(AuthorCreateVM entity)

        {
            if (ModelState.IsValid)
            {
                //TODO:Model Mapping :Auto Mapper
                var author = new Author()
                {
                    AuthorName = entity.AuthorName,
                    Description = entity.Description
                };
                var result = _authorService.Create(author);
                if (result.IsSucced)
                {
                    ModelState.Clear();
                    return RedirectToAction(nameof(Index));

                }
                if (result.ErrorMessages.Any())
                {
                    foreach (var error in result.ErrorMessages)
                    {
                        ModelState.AddModelError("", error);
                    }
                }
            }
            return View();
        }
        public IActionResult Edit(int id)
        {
            var existingAuthor = _authorService.GetFirstOrDefault(x => x.Id == id);
            var author = new AuthorEditVM()
            {
                Id = existingAuthor.Id,
                AuthorName = existingAuthor.AuthorName,
                Description = existingAuthor.Description
            };

            return View(author);
        }


        [HttpPost]
        public IActionResult Edit(AuthorEditVM editModel)
        {
            var existingAuthor = _authorService.GetFirstOrDefault(x => x.Id == editModel.Id);
            if (existingAuthor == null)
            {
                ViewBag.Message = "Requested Page Not Found";
                return View("_NotFound");
            }
            existingAuthor.AuthorName = editModel.AuthorName;
            existingAuthor.Description = editModel.Description;

            var result = _authorService.Update(existingAuthor);
            if (result.IsSucced)
            {
                ModelState.Clear();
                return RedirectToAction(nameof(Index));
            }
            if (result.ErrorMessages.Any())
            {
                foreach (var error in result.ErrorMessages)
                {
                    ModelState.AddModelError("", error);
                }
            }
            return View();
        }
        public IActionResult Details(int id)
        {
            var existingAuthor = _authorService.GetFirstOrDefault(x => x.Id == id);
            if (existingAuthor == null)
            {
                ViewBag.Message = "Requested Page Not Found";
                return View("_NotFound");
            }
            var author = new AuthorDetailsVM()
            {
                Id = existingAuthor.Id,
                AuthorName = existingAuthor.AuthorName,
                Description = existingAuthor.Description
            };

            return View(author);

        }
        public IActionResult Delete(int id)
        {
            var existingAuthor = _authorService.GetFirstOrDefault(x => x.Id == id);
            if (existingAuthor == null)
            {
                ViewBag.Message = "Requested Page Not Found";
                return View("_NotFound");
            }
            var author = new AuthorDeleteVM()
            {
                Id = existingAuthor.Id,
                AuthorName = existingAuthor.AuthorName,
                Description = existingAuthor.Description
            };
            return View(author);

        }

        [HttpPost]
        public IActionResult Delete(AuthorDeleteVM deleteModel)
        {

            var existingAuthor = _authorService.GetFirstOrDefault(x => x.Id == deleteModel.Id);
            if (existingAuthor == null)
            {
                ViewBag.Message = "Requested Page Not Found";
                return View("_NotFound");
            }
            existingAuthor.AuthorName = deleteModel.AuthorName;
            existingAuthor.Description = deleteModel.Description;

            var result = _authorService.Remove(existingAuthor);
            if (result.IsSucced)
            {
                ModelState.Clear();
                return RedirectToAction(nameof(Index));
            }
            if (result.ErrorMessages.Any())
            {
                foreach (var error in result.ErrorMessages)
                {
                    ModelState.AddModelError("", error);
                }
            }
            return View();
        }

    }

}

E-Library/E-Library/Views/Author/Create.cshtml
@model E_Library.Models.BooksAuthor.AuthorCreateVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Author CreateVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AuthorName" class="control-label"></label>
                <input asp-for="AuthorName" class="form-control" />
                <span asp-validation-for="AuthorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" class="btn btn-outline-success" value="Create" />
                <a class="btn btn-info" asp-action="Index" asp-controller="Author"> <i class="fa-solid fa-arrow-right-to-bracket"></i>&nbsp;Back To List</a>
            </div>
        </form>
    </div>
</div>

@section scripts{
        <partial name="~/Views/Shared/_ValidationScriptsPartial.cshtml"></partial>
        <script src="#"></script>
}

E-Library/E-Library/Views/Author/Delete.cshtml
@model E_Library.Models.BooksAuthor.AuthorDeleteVM

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<div>
    <h4>Author DeleteVM</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorName)
        </dd>
       
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <h4 class="text-danger">Do you want to Delete this Category..?</h4>
        <input type="submit" class="btn btn-outline-danger" value="Delete Data" />
        <a class="btn btn-info" asp-action="Index" asp-controller="Author"><i class="fa-solid fa-arrow-right-to-bracket"></i>&nbsp; Back To List</a>

    </form>
</div>

E-Library/E-Library/Views/Author/Details.cshtml
@model E_Library.Models.BooksAuthor.AuthorDetailsVM

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Author DetailsVM</h4>
    <hr />
    <dl class="row">
       
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorName)
        </dd>

    </dl>
    <dl class="row">


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<a class="btn btn-outline-success" asp-action="Edit" asp-route-id="@Model.Id"><i class="fa-solid fa-arrow-right-to-bracket"></i>&nbsp;Edit Data</a>
<a class="btn btn-info" asp-action="Index" asp-controller="Author"><i class="fa-solid fa-arrow-right-to-bracket"></i>&nbsp;Back To List</a>

E-Library/E-Library/Views/Author/Edit.cshtml
@model E_Library.Models.BooksAuthor.AuthorEditVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Author EditVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="AuthorName" class="control-label"></label>
                <input asp-for="AuthorName" class="form-control" />
                <span asp-validation-for="AuthorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>


            <div class="form-group">
                
                <input type="submit" class="btn btn-outline-success" value="Update Data" />
                <a class="btn btn-info" asp-action="Index" asp-controller="Author"> <i class="fa-solid fa-arrow-right-to-bracket"></i>&nbsp;Back To List</a>
            </div>
        </form>
    </div>
</div>

E-Library/E-Library/Views/Author/Index.cshtml
@using E_Library.Models.BooksAuthor
@model IEnumerable<AuthorListVM>

@{
    ViewData["Title"] = "Index";
    int serialNo = 1;
}
<h1 style="color:green; text-align:center">Book Author Index</h1>
<br />
<a class="btn btn-success" asp-action="Create" asp-controller="Author"> <i class="fa-solid fa-arrow-right-to-bracket"></i>&nbsp;New Author</a>

<table border="3" class="table table-bordered table-hover table-striped">
    <thead class="text-center">
        <tr>
            <th>
              Serial No
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuthorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
           
            <th>Actions</th>
        </tr>
    </thead>

    @if(!Model.Any())
    {
        <h3>ViewBag.Message</h3>
    }
    else
    {
        <tbody class="text-center">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @(serialNo++)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AuthorName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>

                    <partial name="_ButtonPartial" model="@item.Id" />
                </tr>
            }
        </tbody>
    }
   
</table>